import type { Task } from "./types";

export const TASK_EVENT_STATUS_MAP: Readonly<Partial<Record<string, Task["status"]>>> = {
  task_created: "pending",
  task_queued: "queued",
  task_dequeued: "planning",
  task_resumed: "executing",
  plan_created: "planning",
  plan_revised: "planning",
  executing: "executing",
  progress_update: "executing",
  step_started: "executing",
  step_completed: "executing",
  tool_call: "executing",
  tool_result: "executing",
  tool_error: "executing",
  verification_passed: "executing",
  file_created: "executing",
  file_modified: "executing",
  file_deleted: "executing",
  artifact_created: "executing",
  task_completed: "completed",
  task_paused: "paused",
  approval_requested: "blocked",
  approval_granted: "executing",
  approval_denied: "failed",
  llm_error: "failed",
  step_timeout: "failed",
  error: "failed",
  task_cancelled: "cancelled",
  task_interrupted: "interrupted",
};
