export const TASK_EVENT_BRIDGE_ALLOWLIST = [
  "task_created",
  "task_queued",
  "task_dequeued",
  "task_paused",
  "task_resumed",
  "task_cancelled",
  "task_completed",
  "plan_created",
  "plan_revised",
  "assistant_message",
  "user_message",
  "progress_update",
  "approval_requested",
  "approval_granted",
  "approval_denied",
  "step_started",
  "step_completed",
  "step_failed",
  "tool_call",
  "tool_error",
  "verification_passed",
  "verification_failed",
  "file_created",
  "artifact_created",
  "file_modified",
  "file_deleted",
  "error",
  "llm_error",
  "step_timeout",
] as const;

export type TaskEventBridgeAllowlistEvent = (typeof TASK_EVENT_BRIDGE_ALLOWLIST)[number];
